In [60]:
import numpy as np


In [61]:
seq1="ATGCT"
seq2="AGCT"

In [62]:
matrix= np.zeros((len(seq1)+1,len(seq2)+1))

In [63]:
match_matrix=np.zeros((len(seq1),len(seq2)))

In [64]:
match=1
mismatch=-1
gap=-2

In [65]:
#Just for check

In [66]:
for i in range(len(seq1)):
  for j in range(len(seq2)):
    if seq1[i]==seq2[j]:
      match_matrix[i][j]=match
    else:
      match_matrix[i][j]=mismatch

In [67]:
print(match_matrix)

[[ 1. -1. -1. -1.]
 [-1. -1. -1.  1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1. -1.]
 [-1. -1. -1.  1.]]


In [68]:
#Needleman Code


In [69]:
# the first row and coloumn

In [70]:
for i in range(len(seq1)+1):
  matrix[i][0]=gap*i
for j in range(len(seq2)+1):
  matrix[0][j]=gap*j

In [71]:
#matrix fill

In [73]:
for i in range(len(seq1)):
  for j in range(len(seq2)):
    matrix[i+1][j+1]=max(matrix[i][j+1]+gap,matrix[i+1][j]+gap,matrix[i][j]+match_matrix[i][j])

print(matrix)

[[  0.  -2.  -4.  -6.  -8.]
 [ -2.   1.  -1.  -3.  -5.]
 [ -4.  -1.   0.  -2.  -2.]
 [ -6.  -3.   0.  -1.  -3.]
 [ -8.  -5.  -2.   1.  -1.]
 [-10.  -7.  -4.  -1.   2.]]


In [ ]:
#trace back

In [78]:
aligned_1=""
aligned_2=""
ti=len(seq1)
tj=len(seq2)

In [81]:
while(ti >0 and tj > 0):
 if (ti >0 and tj > 0 and matrix[ti][tj] == matrix[ti-1][tj-1]+ match_matrix[ti-1][tj-1]):

        aligned_1 = seq1[ti-1] + aligned_1
        aligned_2 = seq2[tj-1] + aligned_2

        ti = ti - 1
        tj = tj - 1
 elif(ti > 0 and matrix[ti][tj] == matrix[ti-1][tj] + gap):
        aligned_1 = seq1[ti-1] + aligned_1
        aligned_2 = "-" + aligned_2

        ti = ti -1
 else:
        aligned_1 = "-" + aligned_1
        aligned_2 = seq2[tj-1] + aligned_2

        tj = tj - 1

In [82]:
print(aligned_1)
print(aligned_2)

ATGCT
A-GCT
