In [1]:
import numpy as np


In [2]:
seq1="ATGCT"
seq2="AGCT"

In [3]:
matrix= np.zeros((len(seq1)+1,len(seq2)+1))

In [4]:
match_matrix=np.zeros((len(seq1),len(seq2)))

In [5]:
match=1
mismatch=-1
gap=-2

In [ ]:
#Just for check

In [6]:
for i in range(len(seq1)):
  for j in range(len(seq2)):
    if seq1[i]==seq2[j]:
      match_matrix[i][j]=match
    else:
      match_matrix[i][j]=mismatch

In [ ]:
print(match_matrix)

[[ 1. -1. -1. -1.]
 [-1. -1. -1.  1.]
 [-1.  1. -1. -1.]
 [-1. -1.  1. -1.]
 [-1. -1. -1.  1.]]


In [ ]:
#Waterman Code


In [ ]:
# the first row and coloumn

In [ ]:
for i in range(len(seq1)+1):
  matrix[i][0]=gap*i
for j in range(len(seq2)+1):
  matrix[0][j]=gap*j

In [ ]:
#matrix fill

In [7]:
for i in range(len(seq1)):
  for j in range(len(seq2)):
    matrix[i+1][j+1]=max(matrix[i][j+1]+gap,matrix[i+1][j]+gap,matrix[i][j]+match_matrix[i][j])
    if matrix[i+1][j+1]<0:
      matrix[i+1][j+1]=0

print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 3.]]


In [ ]:
#trace back

In [8]:
aligned_1=""
aligned_2=""
ti=len(seq1)
tj=len(seq2)

In [9]:
while(ti >0 and tj > 0):
 if (ti >0 and tj > 0 and matrix[ti][tj] == matrix[ti-1][tj-1]+ match_matrix[ti-1][tj-1]):

        aligned_1 = seq1[ti-1] + aligned_1
        aligned_2 = seq2[tj-1] + aligned_2

        ti = ti - 1
        tj = tj - 1
 elif(ti > 0 and matrix[ti][tj] == matrix[ti-1][tj] + gap):
        aligned_1 = seq1[ti-1] + aligned_1
        aligned_2 = "-" + aligned_2

        ti = ti -1
 else:
        aligned_1 = "-" + aligned_1
        aligned_2 = seq2[tj-1] + aligned_2

        tj = tj - 1

In [10]:
print(aligned_1)
print(aligned_2)

-GCT
AGCT
